@BlogAPI_HostAddress = https://localhost:7027

GET {{BlogAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{BlogAPI_HostAddress}}/api/posts
Content-Type: application/json

{
  "title": "Nowy post na blogu",
  "content": "To jest treœæ nowego posta na blogu. Mo¿e zawieraæ ró¿ne informacje i szczegó³y."
}

###
